### ISSUE TITLE
KNOWN ISSUE: Tests for Neighborhood class

### ISSUE THREAD

**Issue by jljardon** [learn-co-curriculum/js-object-oriented-daily-lunch#20]
Tests for Neighborhood class take the following methods as correct:

```
deliveries(){
    return store.deliveries;
  }

  customers() {
    return store.customers;
  }

  meals() {
    return store.meals;
  }
```

However those methods would return all the elements of the array an not the ones that need to be filtered like:

`  deliveries() {
    return store.deliveries.filter(deliveries => deliveries.id = this.id);
  }`

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#22.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
