### ISSUE TITLE
Solution Error

### ISSUE THREAD

**Issue by ChrstphGrnr** [learn-co-curriculum/js-object-oriented-daily-lunch#23]
The solution for this lab has an error `index.js` in line 47 in the #`static byPrice()`

It is currently ` static byPrice() {
      return store.meals.sort((a, b) => a.price < b.price);
    }`

and it should be ` static byPrice() {
      return store.meals.sort((a, b) => b.price - a.price);
    }`

**Comment by maxwellbenton** [comment]
Hi @ChrstphGrnr,

This issue has been corrected. Thank you for opening this issue and letting us know!
